# -*- coding: utf-8 -*-
"""Sentiment Analysis Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jRp-QB_afqCZXUuhOkB9wLRY58bNAfZb
"""

pip install nltk textblob fastapi uvicorn

from textblob import TextBlob
import nltk

# NLTK ka data download karein
nltk.download('punkt')

# Sentiment Analysis Function
def analyze_sentiment(text):
    analysis = TextBlob(text)
    polarity = analysis.sentiment.polarity

    if polarity > 0:
        return "Positive", polarity
    elif polarity < 0:
        return "Negative", polarity
    else:
        return "Neutral", polarity

# Chatbot Function
def chatbot_response(user_input):
    sentiment, polarity = analyze_sentiment(user_input)

    if sentiment == "Positive":
        return f"Wow! You sound happy. 😊 (Sentiment: {sentiment}, Polarity: {polarity})"
    elif sentiment == "Negative":
        return f"Oh no! You seem upset. 😔 (Sentiment: {sentiment}, Polarity: {polarity})"
    else:
        return f"Hmm, interesting. 🤔 (Sentiment: {sentiment}, Polarity: {polarity})"

# Chatbot ko test karein
user_input = input("Enter your text: ")  # Colab me manual input lene ke liye
response = chatbot_response(user_input)
print(response)